
---

- name: Nginx Systemd
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started

- name: Reload Nginx
  systemd:
    name: nginx.service
    state: reloaded

# handlers file for nginx
